apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    # Using Git repository with Helm chart
    repoURL: https://github.com/8gears/n8n-helm-chart.git
    path: charts/n8n
    targetRevision: HEAD
    helm:
      releaseName: n8n
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

