apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    # Using the official OCI Helm chart repository
    repoURL: oci://8gears.container-registry.com/library
    chart: n8n
    targetRevision: 1.0.12
    helm:
      releaseName: n8n
      values: |
        replicaCount: 1

        n8n:
          image:
            repository: n8nio/n8n
            tag: 1.67.3
            pullPolicy: IfNotPresent
          # The encryption key and basic auth password are now loaded from the 'n8n-credentials' secret
          # Create this secret using the command provided in the chat.
          existingSecret: "n8n-credentials"
          webhookUrl: https://n8n.thesugu.com/
          basicAuth:
            enabled: true
            user: "admin"

        ingress:
          enabled: true
          className: nginx
          host: n8n.thesugu.com
          tls:
            enabled: true
            secretName: n8n-thesugu-tls

        postgresql:
          enabled: true
          auth:
            database: n8n
            username: n8n
            password: n8n # For better security, consider managing this with a secret as well.
          primary:
            persistence:
              size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

