apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/a5r0n/charts
    chart: n8n
    targetRevision: 0.3.0
    helm:
      releaseName: n8n
      values: |
        replicaCount: 1

        n8n:
          image:
            repository: n8nio/n8n
            tag: 1.67.3
            pullPolicy: IfNotPresent
          encryptionKey: "CHANGE_ME_LONG_RANDOM"
          webhookUrl: https://n8n.thesugu.com/
          auth:
            enabled: true
            username: "admin"
            password: "CHANGE_ME_STRONG"

        ingress:
          enabled: true
          className: nginx
          host: n8n.thesugu.com
          tls:
            enabled: true
            secretName: n8n-thesugu-tls

        postgresql:
          enabled: true
          auth:
            database: n8n
            username: n8n
            password: n8n
          primary:
            persistence:
              size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

